USE [master]
GO

/****** Object:  Database [EXAMINATION]    Script Date: 1/13/2021 7:21:04 PM ******/
CREATE DATABASE [EXAMINATION]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EXAMINATION', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER\MSSQL\DATA\EXAMINATION.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EXAMINATION_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER\MSSQL\DATA\EXAMINATION_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EXAMINATION].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EXAMINATION] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EXAMINATION] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EXAMINATION] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EXAMINATION] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EXAMINATION] SET ARITHABORT OFF 
GO

ALTER DATABASE [EXAMINATION] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EXAMINATION] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EXAMINATION] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EXAMINATION] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EXAMINATION] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EXAMINATION] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EXAMINATION] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EXAMINATION] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EXAMINATION] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EXAMINATION] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EXAMINATION] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EXAMINATION] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EXAMINATION] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EXAMINATION] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EXAMINATION] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EXAMINATION] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EXAMINATION] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EXAMINATION] SET RECOVERY FULL 
GO

ALTER DATABASE [EXAMINATION] SET  MULTI_USER 
GO

ALTER DATABASE [EXAMINATION] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EXAMINATION] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EXAMINATION] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EXAMINATION] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EXAMINATION] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EXAMINATION] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EXAMINATION] SET  READ_WRITE 
GO


