USE [EXAMINATION]
GO

ALTER TABLE [dbo].[GRADES] DROP CONSTRAINT [FK_GRADES_GRADES_STUDENTS]
GO

ALTER TABLE [dbo].[GRADES]  WITH CHECK ADD  CONSTRAINT [FK_GRADES_GRADES_STUDENTS] FOREIGN KEY([SID])
REFERENCES [dbo].[STUDENTS] ([SID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[GRADES] CHECK CONSTRAINT [FK_GRADES_GRADES_STUDENTS]
GO

ALTER TABLE [dbo].[GRADES] DROP CONSTRAINT [FK_GRADES_GRADES2_EXAMS]
GO

ALTER TABLE [dbo].[GRADES]  WITH CHECK ADD  CONSTRAINT [FK_GRADES_GRADES2_EXAMS] FOREIGN KEY([EID])
REFERENCES [dbo].[EXAMS] ([EID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[GRADES] CHECK CONSTRAINT [FK_GRADES_GRADES2_EXAMS]
GO




