USE [EXAMINATION]
GO

ALTER TABLE [dbo].[ENROLLMENT] DROP CONSTRAINT [FK_ENROLLME_ENROLLMEN_COURSES]
GO

ALTER TABLE [dbo].[ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_ENROLLME_ENROLLMEN_COURSES] FOREIGN KEY([CID])
REFERENCES [dbo].[COURSES] ([CID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ENROLLMENT] CHECK CONSTRAINT [FK_ENROLLME_ENROLLMEN_COURSES]
GO

ALTER TABLE [dbo].[ENROLLMENT] DROP CONSTRAINT [FK_ENROLLME_ENROLLMEN_STUDENTS]
GO

ALTER TABLE [dbo].[ENROLLMENT]  WITH CHECK ADD  CONSTRAINT [FK_ENROLLME_ENROLLMEN_STUDENTS] FOREIGN KEY([SID])
REFERENCES [dbo].[STUDENTS] ([SID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ENROLLMENT] CHECK CONSTRAINT [FK_ENROLLME_ENROLLMEN_STUDENTS]
GO





