USE [EXAMINATION]
GO

ALTER TABLE [dbo].[EXAMS] DROP CONSTRAINT [FK_EXAMS_HAS_COURSES]
GO

ALTER TABLE [dbo].[EXAMS]  WITH CHECK ADD  CONSTRAINT [FK_EXAMS_HAS_COURSES] FOREIGN KEY([CID])
REFERENCES [dbo].[COURSES] ([CID]) ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EXAMS] CHECK CONSTRAINT [FK_EXAMS_HAS_COURSES]
GO


